posts/forms.py
from wtforms import (
    Form,
    SelectField,
    SelectMultipleField,
    StringField,
    TextAreaField,
    URLField,
)
from wtforms.validators import InputRequired

from models import Category, Tag


class CategoryForm(Form):
    name = StringField()


class TagForm(Form):
    name = StringField('Название тега', [InputRequired()])


class PostForm(Form):
    author = StringField('Юзернейм автора', [InputRequired()])
    title = StringField('Название поста', [InputRequired()])
    text = TextAreaField('Текст', [InputRequired()])
    category_id = SelectField(
        'Категория',
        choices=[(g.id, g.name) for g in Category.query.all()],
        validators=[InputRequired()]
    )
    tag = SelectMultipleField(
        'Теги', choices=[(g.id, g.name) for g in Tag.query.all()]
    )
    image_url = URLField(
        'Ссылка на изображение'
    )

posts/blueprint.py
from flask import (Blueprint, Response, abort, redirect, render_template,
                   request, url_for)

from app import db
from models import Category, Post, Tag

from .forms import PostForm, TagForm

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/')
def index():
    posts = Post.query
    page_number = request.args.get('page')
    if page_number and page_number.isdigit():
        page_number = int(page_number)
    else:
        page_number = 1
    part_posts = posts.paginate(page=page_number, per_page=4)
    categories = Category.query.all()
    return render_template(
        'posts/index.html', posts=part_posts, categories=categories
    )


@posts.route('/add_tag', methods=['POST', 'GET'])
def create_tag():
    if request.method == 'POST':
        name = request.form.get('name')
        try:
            tag = Tag(name=name)
            db.session.add(tag)
            db.session.commit()
        except:
            abort(Response('Возникла ошибка при создании тега', 400))
        return redirect(url_for('posts.index'))
    form = TagForm()
    categories = Category.query.all()
    return render_template(
        'posts/add_tag.html',
        form=form,
        categories=categories
    )


@posts.route('/add_post', methods=['POST', 'GET'])
def create_post():
    if request.method == 'POST':
        title = request.form.get('title')
        text = request.form.get('text')
        author = request.form.get('author')
        category_id = request.form.get('category_id')
        tags = request.form.getlist('tag')
        image_url = request.form.get('image_url')
        try:
            post = Post(
                title=title, text=text, author=author, category_id=category_id,
                image_url=image_url
            )
            tag_objects = Tag.query.filter(Tag.id.in_(tags)).all()
            post.tags = tag_objects
            db.session.add(post)
            db.session.commit()
        except:
            abort(Response('Возникла ошибка при создании поста', 400))
        return redirect(url_for('posts.index'))
    form = PostForm()
    categories = Category.query.all()
    return render_template(
        'posts/add_post.html',
        form=form,
        categories=categories
    )


@posts.route('/<string:slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    if not post:
        abort(Response('Страница не найдена', 404))
    categories = Category.query.all()
    return render_template(
        'posts/post.html',
        post=post,
        tags=post.tags,
        category=post.category,
        categories=categories
    )


@posts.route('/category/<int:category_id>')
def posts_category(category_id):
    category = Tag.query.get_or_404(category_id, 'Страница не найдена')
    posts = Post.query.filter(Post.category_id == category.id)
    categories = Category.query.all()
    page_number = request.args.get('page')
    if page_number and page_number.isdigit():
        page_number = int(page_number)
    else:
        page_number = 1
    part_posts = posts.paginate(page=page_number, per_page=4)
    return render_template(
        'posts/category.html',
        posts=part_posts,
        type='category',
        categories=categories,
        category=category
    )


@posts.route('/tag/<int:tag_id>')
def posts_tag(tag_id):
    tag = Tag.query.get_or_404(tag_id, 'Страница не найдена')
    posts = Post.query.filter(Post.tags.contains(tag))
    categories = Category.query.all()
    return render_template(
        'posts/category.html',
        posts=posts,
        type='tag',
        categories=categories
    )


@posts.route('/<string:slug>/edit/', methods=['POST', 'GET'])
def edit_post(slug):
    # Редактирование поста (может любой)
    post = Post.query.filter(Post.slug == slug).first()
    if not post:
        abort(Response('Пост не найден', 404))
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        tags = request.form.getlist('tag')
        post.tags = Tag.query.filter(Tag.id.in_(tags)).all()
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    categories = Category.query.all()
    return render_template(
        'posts/edit_post.html', post=post, form=form, categories=categories
    )

posts/templates/posts/add_post.html
{% extends 'base.html' %} {% set categories = categories %} {% include
'posts/header.html'%} {% include 'posts/slider.html'%} {% block content %}
<div class="row">
  <div class="col-md-12">
    <p align="center" class="category-title">Добавить новый пост</p>
  </div>
</div>
<div class="container">
  <div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method="POST">
      {% for field in form %}
      <div class="form-group">
        {{ field.label(class='control-label') }} {{ field(class='form-control')
        }}
      </div>
      {% endfor %}
      <button type="subnit" class="btn btn-success">Создать</button>
    </form>
  </div>
</div>
{% endblock %}

posts/templates/posts/add_tag.html
{% extends 'base.html' %} {% set categories = categories %} {% include 'posts/header.html'%}
{% include 'posts/slider.html'%} 
{% block content %}
<div class="row">
    <div class="col-md-12">
      <p align="center" class="category-title">Добавить новый тег</p>
    </div>
</div>
<div class="container">
<div class="col-md-6">
<form action="{{ url_for('posts.create_tag') }}" method="POST">
  {% for field in form %}
  <div class="form-group">
      {{ field.label(class='control-label') }}
      {{ field(class='form-control') }}
    </div>
  {% endfor %}
  <button type="subnit" class="btn btn-success">Создать</button>
</form>
</div>
</div>
{% endblock %}

posts/templates/posts/category.html
{% extends 'base.html' %} {% set categories = categories %} {% include 'posts/header.html'%}
{% include 'posts/slider.html'%} {% block content %}

<div class="row">
    <div class="col-md-12">
      <p align="center" class="category-title">Все посты по 
          
        {% if type == 'category' %}
        категории
        {% else %}
        тегу
        {% endif %}
        
        {{ category.name }}</p>
    </div>
</div>
<!-- 4 больших карточки с постами -->
<div class="grid-posts">
  <div class="container">
    <div class="row">
      {% for post in posts.items %}
      <div class="col-md-6">
        <div class="card">
          <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
          <img
            class="card-img-top"
            src="{% if not post.image_url %} https://i.picsum.photos/id/1015/6000/4000.jpg?hmac=aHjb0fRa1t14DTIEBcoC12c5rAXOSwnVlaA5ujxPQ0I {% else %} {{ post.image_url }} {% endif %}"
             alt="Card image cap"
          />
          </a>
          <div class="card-block">
            <h6 class="card-category">{{ post.category.name }}</h6>
            <h4 class="card-title">{{ post.title }}</h4>
            <p class="card-text">{{ post.text }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
        <div class="row">
      <div class="col nav">
        <nav aria-label="Page navigation example" class="navigation-pagination">
          <ul class="pagination">
            <li
              {% if not posts.has_prev %}
              class="page-item disabled"
              {% else %}
              class="page-item"
              {% endif %}
            >
              <a class="page-link" href="./?page={{ posts.prev_num }}"
                >Раньше</a
              >
            </li>

            {% for post in posts.iter_pages() %}
              <li {% if post == posts.page %} class="page-item disabled" {% else %} class="page-item" {% endif %}>
                <a class="page-link" href="./?page={{ post }}">{{ post }}</a>
              </li>
            {% endfor %}

            <li
              {% if not posts.has_next %}
              class="page-item disabled"
              {% else %}
              class="page-item"
              {% endif %}
            >
              <a class="page-link" href="./?page={{ posts.next_num }}">Позже</a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %} {% set categories = categories %} {% include 'posts/header.html'%}
{% include 'posts/slider.html'%} {% block content %}
<div class="row">
    <div class="col-md-12">
      <p align="center" class="category-title">Отредактировать пост</p>
    </div>
</div>
<div class="container">
  <div class="col-md-6">
    <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
      {% for field in form %}
      <div class="form-group">
        {{ field.label(class='control-label') }} {{ field(class='form-control')
        }}
      </div>
      {% endfor %}
      <button type="subnit" class="btn btn-success">Сохранить</button>
    </form>
  </div>
</div>
{% endblock %}

posts/templates/posts/header.html
<!-- меню -->
<header>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{{ url_for('posts.index') }}"
        >БлогПроПутешествия</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          {% for category in categories %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('posts.posts_category', category_id=category.id) }}">{{ category.name }}</a>
          </li>
          {% endfor %}
          <li class="nav-item">
            <a href="{{ url_for('posts.create_post') }}" class="nav-link">Добавить пост</a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('posts.create_tag') }}" class="nav-link">Добавить тег</a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>
<!-- меню -->

posts/templates/posts/index.html
{% extends 'base.html' %} {% set categories = categories%} {%
include 'posts/header.html'%} {% include 'posts/slider.html'%} {% block content
%}
<!-- об авторе-->
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="about-author">
        <h3 class="about-author-title">
          <a href="" class="about-author">Что-то про блог и автора</a>
        </h3>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore
          dignissimos dolorum ut totam libero laboriosam eius. Distinctio
          deserunt ullam minus tempore? Cum nostrum, voluptas facilis dolorum
          labore aut? Fugiat eligendi quidem recusandae consequatur quisquam,
          consequuntur obcaecati adipisci. Animi similique fugit reiciendis
          alias inventore itaque voluptas nesciunt ratione excepturi voluptates
          repellendus, ipsam repudiandae exercitationem sed accusamus
          necessitatibus aliquam, ipsa pariatur quod. Ab, voluptates minima!
          Necessitatibus repellendus nobis molestiae
        </p>
      </div>
    </div>
  </div>
</div>
<!-- об авторе-->

<!-- 4 больших карточки с постами -->
<div class="grid-posts">
  <div class="container">
    <div class="row">
      {% for post in posts.items %}
      <div class="col-md-6">
        <div class="card">
          <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
          <img
            class="card-img-top"
            src="{% if not post.image_url %} https://i.picsum.photos/id/1015/6000/4000.jpg?hmac=aHjb0fRa1t14DTIEBcoC12c5rAXOSwnVlaA5ujxPQ0I {% else %} {{ post.image_url }} {% endif %}"
             alt="Card image cap"
          />
          </a>
          <div class="card-block">
            <h6 class="card-category">{{ post.category.name }}</h6>
            <h4 class="card-title">{{ post.title }}</h4>
            <p class="card-text">{{ post.text[:200] }}...</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="row">
      <div class="col nav">
        <nav aria-label="Page navigation example" class="navigation-pagination">
          <ul class="pagination">
            <li
              {% if not posts.has_prev %}
              class="page-item disabled"
              {% else %}
              class="page-item"
              {% endif %}
            >
              <a class="page-link" href="./?page={{ posts.prev_num }}"
                >Раньше</a
              >
            </li>

            {% for post in posts.iter_pages() %}
              <li {% if post == posts.page %} class="page-item disabled" {% else %} class="page-item" {% endif %}>
                <a class="page-link" href="./?page={{ post }}">{{ post }}</a>
              </li>
            {% endfor %}

            <li
              {% if not posts.has_next %}
              class="page-item disabled"
              {% else %}
              class="page-item"
              {% endif %}
            >
              <a class="page-link" href="./?page={{ posts.next_num }}">Позже</a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
{% endblock %}

posts/templates/posts/post.html
{% extends 'base.html' %}
{% set categories = categories %}
{% include 'posts/header.html'%} 
{% block content %}
    <!-- просмотр поста -->
      <div class="container">
          <div class="row">
            <div class="col">
              <!-- <h8 class="card-header">{{ category }}</h5> -->
              <div class="card-body">
                <h3 class="card-title">{{ post.title }}</h5>
                <img
                  class="card-img-top"
                  src="{% if not post.image_url %} https://i.picsum.photos/id/1015/6000/4000.jpg?hmac=aHjb0fRa1t14DTIEBcoC12c5rAXOSwnVlaA5ujxPQ0I {% else %} {{ post.image_url }} {% endif %}"
                  alt="Card image cap"
                />
                <p class="author-text"><b>Автор: </b> {{ post.author }}</p>
                <p class="author-text"><b>Теги: </b> 
                  {% for tag in post.tags %}
                   {{ tag.name }} &#9679;
                  {% endfor %}
                </p>
                <p class="card-text">{{ post.text }}</p>
                <a href="{{ url_for('posts.edit_post', slug=post.slug) }}" class="btn btn-secondary">Отредактировать</a>
              </div>
            </div>      
          </div>
      </div>
    <!-- просмотр поста -->
{% endblock %}

posts/templates/posts/slider.html
    <!-- слайдер -->
    <div class="container slider">
      <div
        id="carouselExampleSlidesOnly"
        class="carousel slide carousel-fade"
        data-ride="carousel"
      >
        <div class="carousel-inner">
          <div class="carousel-item">
            <img
              src="https://picsum.photos/id/1018/1180/480"
              class="d-block w-100"
              alt="..."
            />
          </div>
          <div class="carousel-item active">
            <img
              src="https://picsum.photos/id/1040/1180/480"
              class="d-block w-100"
              alt="..."
            />
          </div>
          <div class="carousel-item">
            <img
              src="https://picsum.photos/id/179/1180/480"
              class="d-block w-100"
              alt="..."
            />
          </div>
        </div>
      </div>
    </div>
    <!-- слайдер -->